services:
  weather-app-fe-dev:
    hostname: weather-app-fe-dev
    container_name: weather-app-fe-dev
    restart: unless-stopped
    build:
      context: ../fe
      dockerfile: Dockerfile
      target: fe-dev
      args:
        DOCKER_BUILDKIT: 1
    user: ${UID}:${GID}
    environment:
      - CLIENT_PORT=5611
      - WEATHER_APP_API_URL=https://api.weatherapi.com/v1
      - WEATHER_APP_API_KEY=${WEATHER_APP_API_KEY}
      - NODE_ENV=development
    volumes:
      - ../fe:/home/node/weather-app:rw
      - ./cache:/home/node/.npm:rw
    stop_grace_period: 2s
    tty: true
    stdin_open: true
    ports:
      - "5611:5611"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' http://localhost:5611 | grep -q '200'"
        ]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 30s
    command: npm run _install-start
